version: '3.3'

services:
  redis:
    image: redis:3.2.9
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3.6.10-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks:
      - network

  mongo:
    image: mongo:3.4.6
    hostname: mongo
    ports:
      - "27017:27017"
    entrypoint: /entrypoint.sh mongod --storageEngine wiredTiger
    volumes:
      - mongo-data:/data/db
    networks:
      - network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 1g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - network

volumes:
  redis-data:
    external:
      name: redis-volume
  rabbit-data:
    external:
      name: rabbit-volume
  mongo-data:
    external:
      name: mongo-volume
  elasticsearch-data:
    external:
      name: elasticsearch-volume

networks:
  network:
